schema_version: 1

context:
  version: 3.3.8

package:
  name: types-futures
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-futures/types-futures-${{ version }}.tar.gz
  sha256: 6fe8ccc2c2af7ef2fdd9bf73eab6d617074f09f30ad7d373510b4043d39c42de

build:
  number: 3
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

  - package_contents:
      site_packages:
        - concurrent-python2-stubs/futures/__init__.pyi

about:
  summary: Typing stubs for futures
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed
  repository: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
